version: "2.0"
services:

  ftp:
    container_name: ftp
    image: delfer/alpine-ftp-server
    networks:
    - disks
    restart: unless-stopped
    environment:
    - USERS="dcfs|UszatekM*01"
    - ADDRESS="ftp.dcfs.pw"
    ports:
    - 2021:21

  sftp:
    container_name: sftp
    image: atmoz/sftp
    networks:
    - disks
    restart: unless-stopped
    command: dcfs:UszatekM*01:1001
    ports:
    - 2022:22

networks:
  disks: